### ISSUE TITLE
User story: Player

### ISSUE THREAD

**Issue by faradayDK** [faradayDK/SupperMassiveFabBreakout#1]
Create a class for player (moving square)

**Comment by faradayDK** [comment]
move it to the left or right with a keyboards.

**Comment by EdeaTaka** [comment]
Taken

**Comment by faradayDK** [comment]
SCRUM Template
*User Story for "player":
As a user I'm able to controll the "moving box" to redirect the ball during the gameplay.
Time estimation: 2 days.
Priority: Very high
